In [2]:
# 1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written code and functions that can be imported and used in Python scripts or programs. These libraries contain modules, which are files containing Python code that define functions, classes, and variables. Libraries serve as reusable sets of tools and functionalities that help developers perform common tasks without having to write code from scratch.

Here are some reasons why we use Python libraries:

1. **Code Reusability:**
   - Libraries provide pre-built functions and modules that can be reused across different projects, saving time and effort. Developers don't need to reinvent the wheel for common tasks.

2. **Efficiency:**
   - Using established libraries allows developers to leverage optimized and well-tested code, leading to more efficient and reliable solutions. This is especially important for complex tasks or specialized domains.

3. **Productivity:**
   - Python libraries enhance productivity by providing high-level abstractions and tools that simplify coding. Developers can focus on the specific requirements of their projects without getting bogged down by low-level details.

4. **Community Contribution:**
   - The Python community actively contributes to the development of libraries, ensuring that they are continually improved, updated, and expanded. This collaborative effort results in a rich ecosystem of libraries covering a wide range of domains.

5. **Specialized Functionalities:**
   - Python libraries cater to various domains and industries, offering specialized functionalities. For example, libraries like NumPy for numerical computing, Pandas for data manipulation, TensorFlow for machine learning, and Django for web development.

6. **Interoperability:**
   - Python libraries often provide interoperability with other languages and systems. This allows developers to integrate Python code with existing software and take advantage of the strengths of different technologies.

7. **Scalability:**
   - Libraries help in building scalable solutions as they provide well-structured and modular code. This makes it easier to scale projects and maintain codebases as they grow in complexity.

8. **Documentation and Support:**
   - Libraries typically come with extensive documentation and community support, making it easier for developers to understand how to use them effectively. This reduces the learning curve and facilitates collaboration.

In [4]:
# 2. What is the difference between Numpy array and List?

NumPy arrays and Python lists are both used to store collections of data, but they have some key differences in terms of functionality, performance, and usage. Here are some of the main differences between NumPy arrays and lists:

1. **Data Type:**
   - NumPy arrays are homogeneous, meaning all elements must be of the same data type. This homogeneity allows for more efficient storage and operations.
   - Python lists are heterogeneous, allowing elements of different data types to be mixed in the same list.

2. **Performance:**
   - NumPy arrays are more efficient for numerical operations compared to Python lists. NumPy operations are implemented in C and Fortran, making them faster for large datasets and numerical computations.
   - Python lists are more versatile but may be slower for numerical computations due to their dynamic and heterogeneous nature.

3. **Memory Efficiency:**
   - NumPy arrays are more memory-efficient than Python lists. NumPy uses a fixed, more compact memory layout for arrays, whereas lists have additional overhead for dynamic resizing and storing different data types.
   - NumPy arrays can be more memory-efficient when dealing with large datasets.

4. **Functionality:**
   - NumPy provides a wide range of mathematical functions and operations that can be applied directly to entire arrays, making it convenient for numerical computing.
   - Lists have a more general-purpose functionality, but mathematical operations need to be implemented using loops or list comprehensions.

5. **Syntax:**
   - NumPy provides a syntax for array programming that is more concise and closer to mathematical notation, making it easier to work with large datasets and perform array operations.
   - Lists have a more straightforward syntax but require more explicit looping for operations on elements.

6. **Size and Shape:**
   - NumPy arrays have a fixed size at creation, and their size cannot be changed without creating a new array. The shape of a NumPy array is fixed once it is created.
   - Lists are dynamic and can be resized or modified after creation. Lists can easily change in size and shape during runtime.

7. **Use Cases:**
   - NumPy is particularly suitable for numerical computations, scientific computing, and data analysis tasks where performance is crucial.
   - Lists are more general-purpose and can be used in a wide range of scenarios where numerical performance is not a primary concern.


Ques-3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [9]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Original Array is : \n", arr)
print("\nShape of the array is : ", arr.shape)
print("Size of the array is : ", arr.size)
print("Dimension of the array is : ", arr.ndim)

Original Array is : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape of the array is :  (3, 4)
Size of the array is :  12
Dimension of the array is :  2


Ques-4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [10]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
print("First row of the array is : ", arr[0])

First row of the array is :  [1 2 3 4]


Ques-5. How do you access the element at the third row and fourth column from the given numpy array?

In [13]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
print("Element present at 3rd row and 4th column is : ", arr[2][3])

Element present at 3rd row and 4th column is :  12


Ques-6. Write code to extract all odd-indexed elements from the given numpy array?

In [16]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
print("All odd-indexed elements of the array are : \n")
print(arr[:, 1::2])

All odd-indexed elements of the array are : 

[[ 2  4]
 [ 6  8]
 [10 12]]


Ques-7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [20]:
import numpy as np

# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

# Print the result
print(random_matrix)

[[0.50936753 0.15152945 0.0573162 ]
 [0.81867521 0.62947758 0.34144344]
 [0.68708436 0.79067203 0.72127862]]


numpy.random.rand:

This function generates random numbers from a uniform distribution over the half-open interval [0.0, 1.0). In other words, the generated values are uniformly distributed between 0 (inclusive) and 1 (exclusive).

In [22]:
import numpy as np

# Generate a 2x2 matrix with random values between 0 and 1
random_array = np.random.rand(2, 2)
random_array

array([[0.19396325, 0.98834757],
       [0.82703247, 0.6585568 ]])

numpy.random.randn:

This function generates random numbers from a standard normal distribution (mean=0, standard deviation=1). The resulting values are not uniformly distributed; instead, they follow a bell-shaped curve, which is characteristic of a normal (Gaussian) distribution.

In [24]:
import numpy as np

# Generate a 2x2 matrix with random values from a standard normal distribution
random_array_normal = np.random.randn(2, 2)
random_array_normal

array([[ 0.87408785, -1.45726307],
       [ 0.04149657, -0.15561661]])

Ques-9. Write code to increase the dimension of the following array?

In [25]:
import numpy as np

# Original 1D array
original_array = np.array([1, 2, 3, 4, 5])

# Alternatively, you can use numpy.expand_dims
new_dimension_array = np.expand_dims(original_array, axis=1)

# Print the results
print("Original 1D Array:")
print(original_array)
print("\nArray with Increased Dimension:")
print(new_dimension_array)


Original 1D Array:
[1 2 3 4 5]

Array with Increased Dimension:
[[1]
 [2]
 [3]
 [4]
 [5]]


Ques-10. How to transpose the following array in NumPy?

In [26]:
import numpy as np

# Original array
original_array = np.array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Transpose the array using numpy.transpose
transposed_array_1 = np.transpose(original_array)

# Alternatively, you can use the T attribute
transposed_array_2 = original_array.T

# Print the results
print("Original Array:")
print(original_array)
print("\nTransposed Array using TRANSPOSE function :")
print(transposed_array_1)
print("\nTransposed Array using .T :")
print(transposed_array_2)


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed Array using TRANSPOSE function :
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

Transposed Array using .T :
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [29]:
import numpy as np

# Given matrices
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

# 1. Index wise multiplication
index_wise_multiplication = A2 * B2

# 2. Matrix multiplication
matrix_multiplication = np.dot(A2, B2.T)  # Transpose of B for proper matrix multiplication

# 3. Add both the matrices
matrix_addition = A2 + B2

# 4. Subtract matrix B from A
matrix_subtraction = A2 - B2

# 5. Divide matrix B by A (element-wise division)
matrix_division = B2 / A2

# Print the results
print("1. Index Wise Multiplication:")
print(index_wise_multiplication)

print("\n2. Matrix Multiplication:")
print(matrix_multiplication)

print("\n3. Matrix Addition:")
print(matrix_addition)

print("\n4. Matrix Subtraction:")
print(matrix_subtraction)

print("\n5. Matrix Division (Element-wise):")
print(matrix_division)


1. Index Wise Multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

2. Matrix Multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

3. Matrix Addition:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

4. Matrix Subtraction:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

5. Matrix Division (Element-wise):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [30]:
#Ques-12. Which function in Numpy can be used to swap the byte order of an array?

In NumPy, you can use the numpy.byteswap function to swap the byte order of an array. This function is particularly useful when dealing with data that might have been read or written with a different byte order, such as when working with binary files.

In [33]:
import numpy as np

# Create an array with a specified dtype and byte order
original_array = np.array([1, 2, 3, 4], dtype='int32')

# Swap the byte order using numpy.byteswap
swapped_array = original_array.byteswap

# Print the original and swapped arrays
print("Original Array:")
print(original_array)

print("\nSwapped Array:")
print(swapped_array)


Original Array:
[1 2 3 4]

Swapped Array:
<built-in method byteswap of numpy.ndarray object at 0x7f0af82812f0>


In [34]:
#Ques-13. What is the significance of the np.linalg.inv function?

The np.linalg.inv function in NumPy is used to compute the multiplicative inverse of a matrix. In other words, it calculates the inverse of a given square matrix. The significance of np.linalg.inv lies in its application to solving linear systems of equations and its use in various mathematical and scientific computations.

Here are some key aspects of the np.linalg.inv function:

1. Matrix Inversion

2. Linear Systems of Equations

3. Numerical Stability

While theoretically, the inverse exists for a non-singular (invertible) matrix, in numerical computations, matrices may be ill-conditioned or close to singular. Therefore, it is essential to consider the numerical stability of the inversion process, and other methods (like solving linear systems) may be preferred in certain situations.

4. Application in Statistics and Optimization

The inverse of a matrix is often used in statistics, optimization, and various mathematical algorithms. For example, in linear regression, the matrix inversion is used to calculate the coefficients of the regression equation.

In [35]:
import numpy as np

# Create a square matrix
A = np.array([[2, 1],
              [7, 4]])

# Calculate the inverse of the matrix
A_inv = np.linalg.inv(A)

# Print the original and inverse matrices
print("Original Matrix:")
print(A)

print("\nInverse Matrix:")
print(A_inv)


Original Matrix:
[[2 1]
 [7 4]]

Inverse Matrix:
[[ 4. -1.]
 [-7.  2.]]


In [36]:
#Ques-14. What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape of an array without changing its data. It allows you to give a new shape to an array without changing the original data.

In [41]:
import numpy as np

# Reshape a 1D array to a 2D array
arr1 = np.zeros((6,4))
arr2 = np.reshape(arr1, (3, 8))
print("Original array:")
print(arr1)
print()
print("Reshaped array:")
print(arr2)

Original array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Reshaped array:
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [43]:
#Ques-15. What is broadcasting in Numpy?

Broadcasting is a powerful feature in NumPy that allows for implicit element-wise operations between arrays of different shapes and sizes. It enables NumPy to perform operations on arrays of different shapes, as long as they meet certain compatibility conditions. Broadcasting eliminates the need for explicit loops and makes code more concise and efficient.

The basic idea behind broadcasting is to extend smaller arrays so that they have compatible shapes for element-wise operations with larger arrays. NumPy automatically performs these extensions when operating on arrays with different shapes, making it look as if the smaller array were replicated along certain dimensions.

The key rules for broadcasting are:

1. Dimensions Compatibility:

The dimensions of the arrays must be compatible. Broadcasting starts from the trailing dimensions, and for each dimension, the size must either be the same or one of them must be 1.

2. Size Compatibility:

Sizes are compatible if, for each dimension, the sizes are equal or one of them is 1. If a dimension size is 1, the array with size 1 is "broadcast" along that dimension to match the larger array.

In [44]:
import numpy as np

# Example 1: Scalar and 1D array
scalar = 5
arr1d = np.array([1, 2, 3, 4])
result = scalar * arr1d  # Scalar is broadcasted to the shape of arr1d
print("Scalar multiplied by 1D array:")
print(result)

# Example 2: 1D and 2D arrays
arr1d = np.array([1, 2, 3])
arr2d = np.array([[4, 5, 6],
                  [7, 8, 9]])
result = arr1d + arr2d  # arr1d is broadcasted to the shape of arr2d
print("\n1D array added to 2D array:")
print(result)

# Example 3: 2D arrays with different dimensions
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4],
                 [5]])
result = arr1 + arr2  # Both arrays are broadcasted to shape (2, 3)
print("\n2D arrays with different dimensions added:")
print(result)


Scalar multiplied by 1D array:
[ 5 10 15 20]

1D array added to 2D array:
[[ 5  7  9]
 [ 8 10 12]]

2D arrays with different dimensions added:
[[5 6 7]
 [6 7 8]]
